version: 2
jobs:

  deploy:
    macos:
      xcode: "10.2.1"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: deploy
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle install
      # - run:
      #     name: Lint Podspec
      #     command: pod spec lint --verbose --allow-warnings
      - run:
          name: Push Podspec
          command: pod trunk push GravtySDK.podspec

workflows:
  version: 2
  build-test:
    jobs:
      - deploy:
          filters:
            branches:
              only: 
                - master
