version: 2.1
jobs:

  deploy:
    macos:
      xcode: "15.3.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: deploy
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Lint Podspec
          command: pod spec lint --verbose --allow-warnings
      - run:
          name: Push Podspec
          command: pod trunk push GravtySDK.podspec

workflows:
  version: 2.1
  build-test:
    jobs:
      - deploy:
          filters:
            branches:
              only: 
                - master
